import os
from PIL import Image
import streamlit as st


st.title("Gallery 🖼️")

st.write("This is where you can see images generated by other users.")

# Get a list of all the image files in the 'img' folder
img_files = [f for f in os.listdir('img') if f.endswith(('.png', '.jpg', '.jpeg'))]

columns = st.columns(5, gap="large")

# Display the images in a grid
for i in range(len(img_files)):
    img_path = os.path.join('img', img_files[i])
    img = Image.open(img_path)
    img_resized = img.resize((28*5, 28*5))
    columns[i % 5].write('')
    columns[i % 5].image(img_resized)





